[package]
name = "mb-mail-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.5", features = ["tracing", "macros"] }
expect-test = "1.5.0"
handlebars = { version = "5.1.2", features = ["rust-embed"] }
html2text = "0.12.4"
listenfd = "1.0.1"
mrml = { version = "3.1.4", features = [] }
rust-embed = { version = "8.3.0", features = ["include-exclude"] }
serde_json = "1.0.115"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.2", features = ["timeout", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
utoipa = { version = "4.2.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"] }

[profile.release]
lto = true
codegen-units = 1
