[package]
name = "mb-mail-service"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.5", features = ["tracing", "macros"] }
expect-test = "1.5.0"
handlebars = { version = "5.1.2", features = ["rust-embed"] }
html2text = "0.12.5"
lettre = { version = "0.11.7", features = ["tokio1", "builder", "smtp-transport", "pool", "tokio1-rustls-tls", "tracing"], default-features = false }
listenfd = "1.0.1"
mrml = { version = "4.0.0", features = [] }
rust-embed = { version = "8.4.0", features = ["include-exclude"] }
serde_json = "1.0.117"
strum = "0.26.2"
strum_macros = "0.26.4"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.2", features = ["timeout", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
utoipa = { version = "4.2.3", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "7.1.0", features = ["axum"] }

[profile.release]
lto = true
codegen-units = 1
